### ISSUE TITLE
Ensure all codes are running for Syntax

### ISSUE THREAD

**Issue by YenTonv** [YenTonv/CSB340_Mini-Compiler#5]
1jc to ensure all codes are running for syntax

**Comment by 1jc** [comment]
Screen shot   
![screenshot for damo pythonsyntax](https://github.com/YenTonv/CSB340_Mini-Compiler/assets/34551673/7ace549a-9d09-4954-846c-167f0865f1a0)

**Comment by 1jc** [comment]
PythonSyntax run well program 1jc see screen shot above May 12

**Comment by 1jc** [comment]
pic fo reviseSyntax ensuring codes ran 1jc
![pic run for program reviseSyntax](https://github.com/YenTonv/CSB340_Mini-Compiler/assets/34551673/2fe4a30b-d02a-4819-8c39-42db23227f6b)
