### ISSUE TITLE
Three screenshot of your Git work

### ISSUE THREAD

**Issue by YenTonv** [YenTonv/CSB340_Mini-Compiler#8]
1jc to provide screen shots of work  see pull #10

**Comment by 1jc** [comment]
1jc to include three screen shots of work
![sceenshot 2](https://github.com/YenTonv/CSB340_Mini-Compiler/assets/34551673/43690b7b-d535-43cb-996a-66a55edd93c7)

![screenshot 3](https://github.com/YenTonv/CSB340_Mini-Compiler/assets/34551673/f950c4ff-f03a-43f7-8a42-2bc6fefeba84)

![screenshot 4](https://github.com/YenTonv/CSB340_Mini-Compiler/assets/34551673/4fbd6957-d453-40b7-b6cf-a0302ab15bdc)

**Comment by 1jc** [comment]
1jc upload three screen shots of work

**Comment by 1jc** [comment]
1jc to upload screen shot of pull request #10 for pull request

![pic pull 10 on syntax](https://github.com/YenTonv/CSB340_Mini-Compiler/assets/34551673/556f94a0-11ab-4049-b74b-e9b6d3c5850b)

**Comment by 1jc** [comment]
1jc to provide screen shot of pull #10
